version: 0.0
os: linux
files:
  - source: Dockerfile
    destination: /opt/webapp
  - source: index.html
    destination: /opt/webapp
hooks:
  ApplicationStop:
    - location: deploy/application-stop.sh
  BeforeInstall:
    - location: deploy/before-install.sh
  AfterInstall:
    - location: deploy/after-install.sh
  ApplicationStart:
    - location: deploy/application-start.sh