version: 0.0

os: linux
hooks:
  ApplicationStop:
    - location: deploy/application-stop.sh
  BeforeInstall:
    - location: deploy/before-install.sh
  AfterInstall:
    - location: deploy/after-install.sh
  ApplicationStart:
    - location: deploy/application-start.sh