version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr-public get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_REPO_URL
  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t docker-nginx .
      - docker tag docker-nginx:latest $IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo "Pushing the Docker image..."
      - docker push $IMAGE_REPO_NAME:$IMAGE_TAG